name: libread_ryan
version: 1.0.0+1
publish_to: none
description: Project akhir UKK RPL 2024
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flexi_image_slider: ^1.0.8
  pretty_dio_logger: ^1.3.1
  auto_size_text: ^3.0.0
  email_validator: ^2.1.16
  carousel_slider: ^4.2.1
  get_storage: ^2.1.1
  google_fonts: ^5.1.0
  lottie: ^2.0.0
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.9.0
  flutter_image_slideshow: ^0.1.6
  flutter_rating_bar: ^4.0.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/image/icon_aplikasi.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - lib/assets/image/
    - lib/assets/buku/
    - lib/assets/background/

